export const drugClasses = [
  { id: 1, class: "Analgesics" },
  { id: 2, class: "Antibiotics" },
  { id: 3, class: "Antivirals" },
  { id: 4, class: "Antifungals" },
  { id: 5, class: "Antipyretics" },
  { id: 6, class: "Antihistamines" },
  { id: 7, class: "Anti-inflammatory" },
  { id: 8, class: "Antidepressants" },
  { id: 9, class: "Anxiolytics" },
  { id: 10, class: "Antihypertensives" },
  { id: 11, class: "Diuretics" },
  { id: 12, class: "Bronchodilators" },
  { id: 13, class: "Anticoagulants" },
  { id: 14, class: "Antidiabetics" },
  { id: 15, class: "Hormones" },
  { id: 16, class: "Immunosuppressants" },
  { id: 17, class: "Antineoplastics" },
  { id: 18, class: "Antiemetics" },
  { id: 19, class: "Laxatives" },
  { id: 20, class: "Sedatives" },
];
