export const drugClasses = [
  { id: 1, class: "Analgesics" },
  { id: 2, class: "Antibiotics" },
  { id: 3, class: "Antivirals" },
  { id: 4, class: "Antifungals" },
  { id: 5, class: "Antipyretics" },
  { id: 6, class: "Antihistamines" },
  { id: 7, class: "Anti-inflammatory" },
  { id: 8, class: "Antidepressants" },
  { id: 9, class: "Anxiolytics" },
  { id: 10, class: "Antihypertensives" },
  { id: 11, class: "Diuretics" },
  { id: 12, class: "Bronchodilators" },
  { id: 13, class: "Anticoagulants" },
  { id: 14, class: "Antidiabetics" },
  { id: 15, class: "Hormones" },
  { id: 16, class: "Immunosuppressants" },
  { id: 17, class: "Antineoplastics" },
  { id: 18, class: "Antiemetics" },
  { id: 19, class: "Laxatives" },
  { id: 20, class: "Sedatives" },
];
// export const drugClasses = [
//   { value: "Analgesics", label: "Analgesics" },
//   { value: "Antibiotics", label: "Antibiotics" },
//   { value: "Antivirals", label: "Antivirals" },
//   { value: "Antifungals", label: "Antifungals" },
//   { value: "Antipyretics", label: "Antipyretics" },
//   { value: "Antihistamines", label: "Antihistamines" },
//   { value: "Anti-inflammatory", label: "Anti-inflammatory" },
//   { value: "Antidepressants", label: "Antidepressants" },
//   { value: "Anxiolytics", label: "Anxiolytics" },
//   { value: "Antihypertensives", label: "Antihypertensives" },
//   { value: "Diuretics", label: "Diuretics" },
//   { value: "Bronchodilators", label: "Bronchodilators" },
//   { value: "Anticoagulants", label: "Anticoagulants" },
//   { value: "Antidiabetics", label: "Antidiabetics" },
//   { value: "Hormones", label: "Hormones" },
//   { value: "Immunosuppressants", label: "Immunosuppressants" },
//   { value: "Antineoplastics", label: "Antineoplastics" },
//   { value: "Antiemetics", label: "Antiemetics" },
//   { value: "Laxatives", label: "Laxatives" },
//   { value: "Sedatives", label: "Sedatives" },
// ];
