export const routesOfDrugAdministration = [
  { id: 1, route: "Oral" },
  { id: 2, route: "Intravenous (IV)" },
  { id: 3, route: "Intramuscular (IM)" },
  { id: 4, route: "Subcutaneous (SC)" },
  { id: 5, route: "Topical" },
  { id: 6, route: "Inhalation" },
  { id: 7, route: "Rectal" },
  { id: 8, route: "Vaginal" },
  { id: 9, route: "Sublingual" },
  { id: 10, route: "Buccal" },
  { id: 11, route: "Transdermal" },
  { id: 12, route: "Ophthalmic" },
  { id: 13, route: "Otic (Ear)" },
  { id: 14, route: "Nasal" },
];

// export const routesOfDrugAdministration = [
//   { value: "Oral", label: "Oral" },
//   { value: "Intravenous (IV)", label: "Intravenous (IV)" },
//   { value: "Intramuscular (IM)", label: "Intramuscular (IM)" },
//   { value: "Subcutaneous (SC)", label: "Subcutaneous (SC)" },
//   { value: "Topical", label: "Topical" },
//   { value: "Inhalation", label: "Inhalation" },
//   { value: "Rectal", label: "Rectal" },
//   { value: "Vaginal", label: "Vaginal" },
//   { value: "Sublingual", label: "Sublingual" },
//   { value: "Buccal", label: "Buccal" },
//   { value: "Transdermal", label: "Transdermal" },
//   { value: "Ophthalmic", label: "Ophthalmic" },
//   { value: "Otic (Ear)", label: "Otic (Ear)" },
//   { value: "Nasal", label: "Nasal" },
// ];
